name: Deploy React App to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust as per your project’s Node.js version

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build React App
        run: CI=false npm run build  # React build step

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          AWS_BUCKET_NAME: "reduxs3bucket"
          SOURCE_DIR: "build"  # This is where React generates the output

      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v1
        with:
          distribution_id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
